In [1]:
import numpy as np
import pandas as pd

np.random.seed(101)   # travo a semente para o resultado se repetir

In [2]:
precos = np.array([19.9, 45.0, 8.5, 120.0, 33.75])
print(precos)
print(precos.shape)
print(precos.dtype)   # o array inteiro tem um tipo só

[ 19.9   45.     8.5  120.    33.75]
(5,)
float64


In [3]:
codigos = np.arange(1, 6)   # o 6 não entra
estoque = np.full(5, 100)
print(codigos)
print(estoque)
print(np.zeros(5))
print(np.ones(5))

[1 2 3 4 5]
[100 100 100 100 100]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [4]:
print(np.linspace(0, 1, 5))   # aqui o fim entra
print(np.eye(3))

[0.   0.25 0.5  0.75 1.  ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
vendas = np.random.randint(0, 50, 15)
vendas = vendas.reshape(3, 5)   # 3 semanas por 5 produtos
print(vendas)
print(vendas.shape)

[[31 11 17  6 23]
 [11 47  9 13 40]
 [ 4 40 28  0 46]]
(3, 5)


In [6]:
print(vendas.max())
print(vendas.argmax())   # devolve o índice e não o valor
print(np.unravel_index(vendas.argmax(), vendas.shape))   # converto para linha e coluna
print(vendas.min())
print(vendas.argmin())

47
6
(np.int64(1), np.int64(1))
0
13


In [7]:
print(vendas[0])
print(vendas[1, 2])
print(vendas[:2, 1:])
print(vendas[:2][1:])   # dois colchetes são dois cortes de linha

[31 11 17  6 23]
9
[[11 17  6 23]
 [47  9 13 40]]
[[11 47  9 13 40]]


In [8]:
copia = vendas[0].copy()   # sem o copy eu alteraria o original
copia[:] = 0
print(copia)
print(vendas[0])

[0 0 0 0 0]
[31 11 17  6 23]


In [9]:
promo = estoque.copy()
promo[3:] = 0   # atribuo o valor para a fatia inteira
print(promo)

[100 100 100   0   0]


In [10]:
print(vendas > 30)
print(vendas[vendas > 30])   # uso os booleanos como índice
print(np.where(vendas > 30, 'alta', 'baixa'))

[[ True False False False False]
 [False  True False False  True]
 [False  True False False  True]]
[31 47 40 40 46]
[['alta' 'baixa' 'baixa' 'baixa' 'baixa']
 ['baixa' 'alta' 'baixa' 'baixa' 'alta']
 ['baixa' 'alta' 'baixa' 'baixa' 'alta']]


In [11]:
faturamento = vendas * precos   # cada coluna multiplica pelo seu preço
print(np.round(faturamento, 2))
print(np.round(faturamento.sum(axis=0), 2))   # total por produto
print(np.round(faturamento.sum(axis=1), 2))   # total por semana

[[ 616.9   495.    144.5   720.    776.25]
 [ 218.9  2115.     76.5  1560.   1350.  ]
 [  79.6  1800.    238.      0.   1552.5 ]]
[ 915.4  4410.    459.   2280.   3678.75]
[2752.65 5320.4  3670.1 ]


In [12]:
print(np.round(faturamento.mean(), 2))
print(np.round(faturamento.std(), 2))
print(np.round(np.sqrt(precos), 2))
print(np.round(np.exp(precos/100), 3))
print(np.round(np.sin(np.arange(5)), 3))

782.88
686.55
[ 4.46  6.71  2.92 10.95  5.81]
[1.22  1.568 1.089 3.32  1.401]
[ 0.     0.841  0.909  0.141 -0.757]


In [13]:
try:
    print(1/0)
except ZeroDivisionError as e:
    print('python puro para:', e)

print(1 / np.array([0, 1, 2]))   # o numpy devolve inf e segue

python puro para: division by zero
[inf 1.  0.5]


C:\Users\gusta\AppData\Local\Temp\ipykernel_10792\3078352988.py:6: RuntimeWarning: divide by zero encountered in divide
  print(1 / np.array([0, 1, 2]))   # o numpy devolve inf e segue


In [14]:
ticket = faturamento / vendas
print(np.isnan(ticket).sum())
print(np.isinf(ticket).sum())

1
0


C:\Users\gusta\AppData\Local\Temp\ipykernel_10792\53955375.py:1: RuntimeWarning: invalid value encountered in divide
  ticket = faturamento / vendas


In [15]:
produtos = pd.Series(precos, index=['caneta', 'mochila', 'caderno', 'tenis', 'camiseta'])
print(produtos)
print(produtos['tenis'])

caneta       19.90
mochila      45.00
caderno       8.50
tenis       120.00
camiseta     33.75
dtype: float64
120.0


In [16]:
df = pd.DataFrame(vendas, index=['semana1', 'semana2', 'semana3'], columns=produtos.index)
print(df)

         caneta  mochila  caderno  tenis  camiseta
semana1      31       11       17      6        23
semana2      11       47        9     13        40
semana3       4       40       28      0        46


In [17]:
print(type(df['tenis']))   # coluna sozinha volta como Series
print(type(df[['tenis', 'mochila']]))
print(df.tenis)   # atalho que quebra com nome composto

<class 'pandas.Series'>
<class 'pandas.DataFrame'>
semana1     6
semana2    13
semana3     0
Name: tenis, dtype: int32


In [18]:
df['total'] = df.sum(axis=1)
print(df)
print(df.columns)
print(df.index)

         caneta  mochila  caderno  tenis  camiseta  total
semana1      31       11       17      6        23     88
semana2      11       47        9     13        40    120
semana3       4       40       28      0        46    118
Index(['caneta', 'mochila', 'caderno', 'tenis', 'camiseta', 'total'], dtype='str')
Index(['semana1', 'semana2', 'semana3'], dtype='str')


In [19]:
print(df.loc['semana2'])
print(df.iloc[1])
print(df.loc['semana2', 'tenis'])
print(df.iloc[0:2, 1:3])

caneta       11
mochila      47
caderno       9
tenis        13
camiseta     40
total       120
Name: semana2, dtype: int64
caneta       11
mochila      47
caderno       9
tenis        13
camiseta     40
total       120
Name: semana2, dtype: int64
13
         mochila  caderno
semana1       11       17
semana2       47        9


In [20]:
print(df[df['tenis'] > 20])
print(df[(df['tenis'] > 20) & (df['caneta'] > 10)])   # o parêntese é obrigatório
print(df[(df['tenis'] > 20) | (df['caneta'] > 40)])

Empty DataFrame
Columns: [caneta, mochila, caderno, tenis, camiseta, total]
Index: []
Empty DataFrame
Columns: [caneta, mochila, caderno, tenis, camiseta, total]
Index: []
Empty DataFrame
Columns: [caneta, mochila, caderno, tenis, camiseta, total]
Index: []


In [21]:
print(df[df > 20])   # mantém o tamanho e troca por nan

         caneta  mochila  caderno  tenis  camiseta  total
semana1    31.0      NaN      NaN    NaN        23     88
semana2     NaN     47.0      NaN    NaN        40    120
semana3     NaN     40.0     28.0    NaN        46    118


In [22]:
df.drop('total', axis=1)
print(df.columns)   # sem inplace o original não muda

Index(['caneta', 'mochila', 'caderno', 'tenis', 'camiseta', 'total'], dtype='str')


In [23]:
df.drop('total', axis=1, inplace=True)
print(df.columns)

Index(['caneta', 'mochila', 'caderno', 'tenis', 'camiseta'], dtype='str')


In [24]:
df['teste'] = 0
del df['teste']
print(df.columns)
print((df - df + 1).head(2))

Index(['caneta', 'mochila', 'caderno', 'tenis', 'camiseta'], dtype='str')
         caneta  mochila  caderno  tenis  camiseta
semana1       1        1        1      1         1
semana2       1        1        1      1         1


In [25]:
registros = pd.DataFrame({
    'vendedor': ['Ana', 'Bruno', 'Ana', 'Carla', 'Bruno', 'Carla', 'Ana'],
    'produto':  ['tenis', 'caneta', 'mochila', 'tenis', 'mochila', 'caderno', 'caneta'],
    'qtd':      [12, 8, np.nan, 5, 13, 2, 20],
    'desconto': [0.1, np.nan, np.nan, 0.15, 0.05, np.nan, 0.2]
})
print(registros)

  vendedor  produto   qtd  desconto
0      Ana    tenis  12.0      0.10
1    Bruno   caneta   8.0       NaN
2      Ana  mochila   NaN       NaN
3    Carla    tenis   5.0      0.15
4    Bruno  mochila  13.0      0.05
5    Carla  caderno   2.0       NaN
6      Ana   caneta  20.0      0.20


In [26]:
print(registros.isnull().sum())
registros.info()

vendedor    0
produto     0
qtd         1
desconto    3
dtype: int64
<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   vendedor  7 non-null      str    
 1   produto   7 non-null      str    
 2   qtd       6 non-null      float64
 3   desconto  4 non-null      float64
dtypes: float64(2), str(2)
memory usage: 356.0 bytes


In [27]:
print(registros.dropna())
print(registros.dropna(axis=1))
print(registros.dropna(thresh=4))   # mínimo de valores válidos para manter a linha

  vendedor  produto   qtd  desconto
0      Ana    tenis  12.0      0.10
3    Carla    tenis   5.0      0.15
4    Bruno  mochila  13.0      0.05
6      Ana   caneta  20.0      0.20
  vendedor  produto
0      Ana    tenis
1    Bruno   caneta
2      Ana  mochila
3    Carla    tenis
4    Bruno  mochila
5    Carla  caderno
6      Ana   caneta
  vendedor  produto   qtd  desconto
0      Ana    tenis  12.0      0.10
3    Carla    tenis   5.0      0.15
4    Bruno  mochila  13.0      0.05
6      Ana   caneta  20.0      0.20


In [28]:
registros['qtd'] = registros['qtd'].fillna(registros['qtd'].mean())
registros['desconto'] = registros['desconto'].fillna(0)   # ausência aqui significa sem desconto
print(registros.isnull().sum())

vendedor    0
produto     0
qtd         0
desconto    0
dtype: int64


In [29]:
serie = pd.Series([10.0, np.nan, np.nan, 40.0])
print(serie.ffill())

0    10.0
1    10.0
2    10.0
3    40.0
dtype: float64


In [30]:
print(registros['vendedor'].unique())
print(np.unique(registros['produto']))   # o numpy já devolve ordenado
print(registros['vendedor'].nunique())
print(registros['vendedor'].value_counts())

<StringArray>
['Ana', 'Bruno', 'Carla']
Length: 3, dtype: str
['caderno' 'caneta' 'mochila' 'tenis']
3
vendedor
Ana      3
Bruno    2
Carla    2
Name: count, dtype: int64


In [31]:
registros['preco'] = registros['produto'].apply(lambda p: produtos[p])
registros['receita'] = registros['qtd'] * registros['preco'] * (1 - registros['desconto'])
print(registros.round(2))

  vendedor  produto   qtd  desconto  preco  receita
0      Ana    tenis  12.0      0.10  120.0  1296.00
1    Bruno   caneta   8.0      0.00   19.9   159.20
2      Ana  mochila  10.0      0.00   45.0   450.00
3    Carla    tenis   5.0      0.15  120.0   510.00
4    Bruno  mochila  13.0      0.05   45.0   555.75
5    Carla  caderno   2.0      0.00    8.5    17.00
6      Ana   caneta  20.0      0.20   19.9   318.40


In [32]:
def faixa(valor):
    return 'alta' if valor > 200 else 'baixa'

registros['faixa'] = registros['receita'].apply(faixa)   # passo a função sem parêntese
print(registros[['vendedor', 'receita', 'faixa']].round(2))

  vendedor  receita  faixa
0      Ana  1296.00   alta
1    Bruno   159.20  baixa
2      Ana   450.00   alta
3    Carla   510.00   alta
4    Bruno   555.75   alta
5    Carla    17.00  baixa
6      Ana   318.40   alta


In [33]:
print(registros.sort_values(by='receita'))
print(registros.sort_values(by='receita', ascending=False))
print(registros['faixa'].value_counts())

  vendedor  produto   qtd  desconto  preco  receita  faixa
5    Carla  caderno   2.0      0.00    8.5    17.00  baixa
1    Bruno   caneta   8.0      0.00   19.9   159.20  baixa
6      Ana   caneta  20.0      0.20   19.9   318.40   alta
2      Ana  mochila  10.0      0.00   45.0   450.00   alta
3    Carla    tenis   5.0      0.15  120.0   510.00   alta
4    Bruno  mochila  13.0      0.05   45.0   555.75   alta
0      Ana    tenis  12.0      0.10  120.0  1296.00   alta
  vendedor  produto   qtd  desconto  preco  receita  faixa
0      Ana    tenis  12.0      0.10  120.0  1296.00   alta
4    Bruno  mochila  13.0      0.05   45.0   555.75   alta
3    Carla    tenis   5.0      0.15  120.0   510.00   alta
2      Ana  mochila  10.0      0.00   45.0   450.00   alta
6      Ana   caneta  20.0      0.20   19.9   318.40   alta
1    Bruno   caneta   8.0      0.00   19.9   159.20  baixa
5    Carla  caderno   2.0      0.00    8.5    17.00  baixa
faixa
alta     5
baixa    2
Name: count, dtype: int64


In [34]:
emails = pd.Series(['ana@loja.com', 'bruno@gmail.com', 'carla@loja.com'])
print(emails.apply(lambda x: x.split('@')[1]))
print(emails.str.contains('loja', case=False, na=False).sum())

0     loja.com
1    gmail.com
2     loja.com
dtype: str
2


In [35]:
print(registros.groupby('vendedor'))   # sozinho não calcula nada

In [36]:
print(registros.groupby('vendedor')['receita'].sum())
print(registros.groupby('vendedor')['qtd'].mean())
print(registros.groupby('vendedor').count())
print(registros.groupby('vendedor')['receita'].describe())

vendedor
Ana      2064.40
Bruno     714.95
Carla     527.00
Name: receita, dtype: float64
vendedor
Ana      14.0
Bruno    10.5
Carla     3.5
Name: qtd, dtype: float64
          produto  qtd  desconto  preco  receita  faixa
vendedor                                               
Ana             3    3         3      3        3      3
Bruno           2    2         2      2        2      2
Carla           2    2         2      2        2      2
          count        mean         std    min       25%      50%       75%  \
vendedor                                                                      
Ana         3.0  688.133333  530.524319  318.4  384.2000  450.000  873.0000   
Bruno       2.0  357.475000  280.403194  159.2  258.3375  357.475  456.6125   
Carla       2.0  263.500000  348.603643   17.0  140.2500  263.500  386.7500   

              max  
vendedor           
Ana       1296.00  
Bruno      555.75  
Carla      510.00  


In [37]:
print(registros.groupby('vendedor').sum(numeric_only=True))   # a tabela tem coluna de texto

           qtd  desconto  preco  receita
vendedor                                
Ana       42.0      0.30  184.9  2064.40
Bruno     21.0      0.05   64.9   714.95
Carla      7.0      0.15  128.5   527.00


In [38]:
print(registros.groupby('vendedor').agg({'qtd': 'sum', 'receita': 'max'}))

           qtd  receita
vendedor               
Ana       42.0  1296.00
Bruno     21.0   555.75
Carla      7.0   510.00


In [39]:
print(registros.pivot_table(values='receita', index='vendedor', columns='produto'))

produto   caderno  caneta  mochila   tenis
vendedor                                  
Ana           NaN   318.4   450.00  1296.0
Bruno         NaN   159.2   555.75     NaN
Carla        17.0     NaN      NaN   510.0


In [40]:
temp = registros.set_index('vendedor')
print(temp.loc['Ana'])
print(temp.reset_index().head(3))

          produto   qtd  desconto  preco  receita faixa
vendedor                                               
Ana         tenis  12.0       0.1  120.0   1296.0  alta
Ana       mochila  10.0       0.0   45.0    450.0  alta
Ana        caneta  20.0       0.2   19.9    318.4  alta
  vendedor  produto   qtd  desconto  preco  receita  faixa
0      Ana    tenis  12.0       0.1  120.0   1296.0   alta
1    Bruno   caneta   8.0       0.0   19.9    159.2  baixa
2      Ana  mochila  10.0       0.0   45.0    450.0   alta


In [41]:
fora = ['loja1', 'loja1', 'loja1', 'loja2', 'loja2', 'loja2']
dentro = [1, 2, 3, 1, 2, 3]

hier = list(zip(fora, dentro))
hier = pd.MultiIndex.from_tuples(hier)

metas = pd.DataFrame(np.random.randn(6, 2), index=hier, columns=['meta', 'realizado'])
metas.index.names = ['Loja', 'Mes']
print(metas.round(2))

           meta  realizado
Loja  Mes                 
loja1 1   -2.02       0.74
      2    0.53      -0.59
      3    0.19      -0.76
loja2 1   -0.93       0.96
      2    0.19       1.98
      3    2.61       0.68


In [42]:
print(metas.loc['loja1'].round(2))
print(metas.loc['loja1'].loc[2].round(2))
print(metas.xs(1, level='Mes').round(2))   # corto o nível sem encadear loc

     meta  realizado
Mes                 
1   -2.02       0.74
2    0.53      -0.59
3    0.19      -0.76
meta         0.53
realizado   -0.59
Name: 2, dtype: float64
       meta  realizado
Loja                  
loja1 -2.02       0.74
loja2 -0.93       0.96


In [43]:
cadastro = pd.DataFrame({'vendedor': ['Ana', 'Bruno', 'Carla', 'Diego'],
                         'loja': ['loja1', 'loja1', 'loja2', 'loja2'],
                         'admissao': [2021, 2022, 2020, 2023]})
print(cadastro)

  vendedor   loja  admissao
0      Ana  loja1      2021
1    Bruno  loja1      2022
2    Carla  loja2      2020
3    Diego  loja2      2023


In [44]:
print(pd.merge(registros, cadastro, how='inner', on='vendedor').head())

  vendedor  produto   qtd  desconto  preco  receita  faixa   loja  admissao
0      Ana    tenis  12.0      0.10  120.0  1296.00   alta  loja1      2021
1    Bruno   caneta   8.0      0.00   19.9   159.20  baixa  loja1      2022
2      Ana  mochila  10.0      0.00   45.0   450.00   alta  loja1      2021
3    Carla    tenis   5.0      0.15  120.0   510.00   alta  loja2      2020
4    Bruno  mochila  13.0      0.05   45.0   555.75   alta  loja1      2022


In [45]:
print(pd.merge(registros, cadastro, how='left', on='vendedor')['loja'].isnull().sum())
print(pd.merge(registros, cadastro, how='right', on='vendedor')['produto'].isnull().sum())
# o Diego está no cadastro e não vendeu nada
print(pd.merge(registros, cadastro, how='outer', on='vendedor').shape)

0
1
(8, 9)


In [46]:
primeiras = registros.head(3)
ultimas = registros.tail(3)
print(pd.concat([primeiras, ultimas]))
print(pd.concat([primeiras, ultimas], ignore_index=True))

  vendedor  produto   qtd  desconto  preco  receita  faixa
0      Ana    tenis  12.0      0.10  120.0  1296.00   alta
1    Bruno   caneta   8.0      0.00   19.9   159.20  baixa
2      Ana  mochila  10.0      0.00   45.0   450.00   alta
4    Bruno  mochila  13.0      0.05   45.0   555.75   alta
5    Carla  caderno   2.0      0.00    8.5    17.00  baixa
6      Ana   caneta  20.0      0.20   19.9   318.40   alta
  vendedor  produto   qtd  desconto  preco  receita  faixa
0      Ana    tenis  12.0      0.10  120.0  1296.00   alta
1    Bruno   caneta   8.0      0.00   19.9   159.20  baixa
2      Ana  mochila  10.0      0.00   45.0   450.00   alta
3    Bruno  mochila  13.0      0.05   45.0   555.75   alta
4    Carla  caderno   2.0      0.00    8.5    17.00  baixa
5      Ana   caneta  20.0      0.20   19.9   318.40   alta


In [47]:
a = registros[['vendedor', 'qtd']].head(3)
b = registros[['receita']].head(3)
print(pd.concat([a, b], axis=1).round(2))   # só cola porque os índices batem

  vendedor   qtd  receita
0      Ana  12.0   1296.0
1    Bruno   8.0    159.2
2      Ana  10.0    450.0


In [48]:
esq = cadastro.set_index('vendedor')
dire = registros.groupby('vendedor')[['receita']].sum()
print(esq.join(dire).round(2))   # o join usa o índice
print(esq.join(dire, how='inner').round(2))

           loja  admissao  receita
vendedor                          
Ana       loja1      2021  2064.40
Bruno     loja1      2022   714.95
Carla     loja2      2020   527.00
Diego     loja2      2023      NaN
           loja  admissao  receita
vendedor                          
Ana       loja1      2021  2064.40
Bruno     loja1      2022   714.95
Carla     loja2      2020   527.00


In [49]:
registros.to_csv('vendas.csv', index=False)
lido = pd.read_csv('vendas.csv')
print(lido.shape)
print(lido.describe().round(2))

(7, 7)
         qtd  desconto   preco  receita
count   7.00      7.00    7.00     7.00
mean   10.00      0.07   54.04   472.34
std     5.86      0.08   47.03   411.58
min     2.00      0.00    8.50    17.00
25%     6.50      0.00   19.90   238.80
50%    10.00      0.05   45.00   450.00
75%    12.50      0.12   82.50   532.88
max    20.00      0.20  120.00  1296.00


In [50]:
registros.to_csv('vendas_br.csv', sep=';', decimal=',', index=False)
print(pd.read_csv('vendas_br.csv', sep=';', decimal=',').head(3))

  vendedor  produto   qtd  desconto  preco  receita  faixa
0      Ana    tenis  12.0       0.1  120.0   1296.0   alta
1    Bruno   caneta   8.0       0.0   19.9    159.2  baixa
2      Ana  mochila  10.0       0.0   45.0    450.0   alta


In [51]:
registros.to_excel('vendas.xlsx', sheet_name='Vendas', index=False)
print(pd.read_excel('vendas.xlsx', sheet_name='Vendas').head(3))

  vendedor  produto  qtd  desconto  preco  receita  faixa
0      Ana    tenis   12       0.1  120.0   1296.0   alta
1    Bruno   caneta    8       0.0   19.9    159.2  baixa
2      Ana  mochila   10       0.0   45.0    450.0   alta


In [52]:
# tabelas = pd.read_html('https://...')
# print(tabelas[0].head())
# o read_html devolve uma lista e depende de internet

In [53]:
resumo = registros.groupby('vendedor')['receita'].sum().sort_values(ascending=False)
print(resumo.round(2))
print('quem mais faturou:', resumo.idxmax())
print('total da loja:', round(resumo.sum(), 2))

vendedor
Ana      2064.40
Bruno     714.95
Carla     527.00
Name: receita, dtype: float64
quem mais faturou: Ana
total da loja: 3306.35
